import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { prisma } from '../common/db'

const Home: NextPage = (props) => {
  // console.log(props.links)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {props.host}
        </h1>

        {props.links.map((item) => (
          <pre key={item.id}>{JSON.stringify(item, null, 2)}</pre>
        ))}

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const links = await prisma.link.findMany()

  links.map(x => {
    x.createdAt = Math.floor(x.createdAt / 1000);
    x.updatedAt = Math.floor(x.updatedAt / 1000);
    return x;
  })

  console.log(links);

  return {
    props: {
      host: "avi mehenwal",
      links,
    },
  }
}

export default Home
