import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { ALL_LINKS } from '../graphql/queries'
import styles from '../styles/Home.module.css'
import { apolloClient } from './_app'

interface Links {
  id: number;
  anchorText: string;
  url: string
}
interface HomeProps {
  host: string;
  links: Links[]

}
const Home: NextPage<HomeProps> = ({ host, links }) => {
  // console.log(props.links)
  // const { loading, error, data } = useQuery(ALL_LINKS);
  // if (loading) return 'Loading...';
  // if (error) return `Error! ${error.message}`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {host}
        </h1>

        <ul>
          {links && links?.map(link => (
            <li key={link.id}>
              <a href={link.url} target="_blank" rel='noreferrer'>
                {link.anchorText}
              </a>
            </li>
          ))}
        </ul>

        {/* {props.links.map((item) => (
          <pre key={item.id}>{JSON.stringify(item, null, 2)}</pre>
        ))} */}

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await apolloClient.query({ query: ALL_LINKS })

  return {
    props: {
      links: data.GetAllLinks,
      host: "Avi Mehenwal,"
    },
  }
}

export default Home
